version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fazztrack
      - MYSQL_DATABASE=todolist
    ports:
      - 3307:3306
    volumes:
      - todolist-mysql-data:/var/lib/mysql
      - todolist-mysql-config:/etc/mysql
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DBNAME: todolist
      MYSQL_USER: root
      MYSQL_PASSWORD: fazztrack
      MYSQL_HOST: db
    volumes:
      - ./:/todolist
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  todolist-mysql-data:
  todolist-mysql-config:
